In [2]:
import numpy as np
values = np.arange(10, 50)
values



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
values = np.arange(0, 9)
values.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
identity_mat = np.eye(3,3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
import random
num_values = 27
random_ints = [random.randint(1,1000) for _ in range(num_values)]
values = np.array(random_ints)
values.reshape(3,3,3)
values

array([ 59, 232, 731, 635, 958, 454, 371, 180, 300,  81, 201, 157, 225,
        31, 853, 834, 413, 237, 696, 983, 299, 799, 707, 977, 863, 452,
       274])

In [22]:
import numpy as np
import random
values = np.random.randint(1,1000, size=(3,3,3))
values

array([[[575, 592, 444],
        [977, 571,  52],
        [683, 826, 467]],

       [[782, 603, 875],
        [336, 545, 539],
        [706, 406, 295]],

       [[163, 152, 358],
        [526, 127, 668],
        [238, 919, 734]]], dtype=int32)

In [25]:
values = np.random.randint(1,1000, size=(10,10))
values.min()
values.max()

np.int32(995)

In [26]:
values = np.random.randint(1,1000, size=(30))
values.mean()

np.float64(360.46666666666664)

In [28]:
values = np.random.rand(5,5)
norm_values = ((values-values.min())/(values.max()-values.min()))
norm_values

array([[0.07488981, 0.66376757, 0.75191166, 0.02536165, 0.71339629],
       [0.2823908 , 1.        , 0.83721756, 0.38032539, 0.50797301],
       [0.07438749, 0.        , 0.68894844, 0.26822445, 0.14786583],
       [0.6936043 , 0.4575778 , 0.48627532, 0.66908033, 0.85516715],
       [0.7988733 , 0.37963962, 0.06982398, 0.85027287, 0.07982677]])

In [44]:
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
mul = m1@m2
mul

array([[0.91963447, 0.75545513],
       [1.32671732, 1.17213544],
       [1.42214015, 1.10535309],
       [0.87461944, 1.17736892],
       [1.13877876, 1.11746006]])

In [45]:
m1 = np.random.rand(3,3)
m2 = np.random.rand(3,3)
dot_product = np.dot(m1,m2)
dot_product


array([[0.76579475, 1.27474605, 0.66147987],
       [0.65618697, 1.0228134 , 0.57890642],
       [0.59903664, 1.01895477, 0.52308877]])

In [46]:
mat = np.random.rand(4,4)
transpose = mat.transpose()
transpose

array([[0.86029456, 0.84471164, 0.35295838, 0.18490989],
       [0.99660733, 0.8304949 , 0.56764824, 0.05535133],
       [0.15212242, 0.49844915, 0.17021835, 0.69337687],
       [0.44287537, 0.52209162, 0.21114679, 0.73375609]])

In [47]:

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
determinant = np.linalg.det(matrix)
determinant

np.float64(0.0)

In [53]:
mat1 = np.random.rand(3,4)
mat2 = np.random.rand(4,3)
matrix_product = mat1@mat2
matrix_product

array([[1.11343009, 1.36868002, 0.84943225],
       [1.06715947, 1.57401422, 0.99745195],
       [1.10201421, 0.83408877, 0.8474444 ]])

In [62]:
mata = np.random.rand(3,3)
matb = np.random.rand(3,1)
product = mata@matb
product
matb

array([[0.99167794],
       [0.76299734],
       [0.52564333]])

In [66]:
A = np.random.rand(3,3)
b = [
    [3],
    [4],
    [5]]
x = np.linalg.solve(A, b)
x

array([[ 9.47185961],
       [-7.06941462],
       [ 7.01660051]])

In [72]:
matrix_A = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]
array1 = np.array(matrix_A)
sum = np.sum(matrix_A, axis=0)
sum
sum2 = np.sum(matrix_A, axis=1)
sum2

array([ 15,  40,  65,  90, 115])

In [73]:
pip install pillow

   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------------------------------


[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip
